/**
 * Re-export generated core-engine row contracts.
 * Field names are owned by docs/schema/generated/core-engine-rows.ts — do not invent.
 */
export type {
  AuditColumns,
  AuditEventRow,
  ClauseRow,
  ConversationMessageRow,
  ConversationThreadRow,
  CompletenessRuleRow,
  DocTypeRow,
  DocumentArtifactRow,
  DocumentRow,
  ExcelCellMappingRow,
  ExtractionRow,
  FieldBoxRow,
  FieldDefRow,
  FieldFillRuleRow,
  FindingRow,
  IngestPageRow,
  IngestRunRow,
  JobRow,
  JsonValue,
  LayoutEdgeRow,
  LayoutUnitRow,
  ProjectRow,
  ProposalRow,
  ReceiptRow,
  RuleFixtureRow,
  RuleRow,
  RuleVersionRow,
  SignatureTaskRow,
  SpecPackRow,
  StandardDocRow,
  StandardEdgeRow,
  StandardVersionRow,
  TemplateRow,
  VolumePreviewRow,
} from "../../../docs/schema/generated/core-engine-rows.js";
